### PR TITLE
Refactor Java API for Lua Classes

### PR DESCRIPTION
**Pull request by Adrodoc55**
Refactor Java API for Lua Classes and Remove "Instance" Java Classes.

### CODE REVIEW

**Comment by Adrodoc55** [comment]
I also added that each lua class first requires it's superclass, because otherwise the metatable might not be set. If the `class` function returns a new table every time then there should be a bug wich can cause multiple tables to be instatiated for one class. I don't see where this is prohibited, but debugging suggests that this bug does not exist. So my question is: Does the following code create two tables or just one?
```lua
class('Abc')
class('Abc')
```
If two tables are created and the second call just overwrites the registered class table then we might need to add something like this to the class function:
```lua
if _G[name] ~= nil then
  return _G[name]
end
```
But then the question is: Should the superclass (metatable) be updated in the following example?
```lua
class('Abc')
class('Abc', MySuperclass)
```

**Comment by mkarneim** [comment]
Concerning your question about the 'class' function: multiple invocations of class(n) for the same n should be prohibited by throwing an error.

**Comment by Adrodoc55** [comment]
@mkareim if that is the case then each lua class should start with a nullcheck, because it May have been required before:
```lua
if MyFunnyClass == nil then
  return
End
```

**Comment by mkarneim** [comment]
As always you are complete right :-)

**Comment by Adrodoc55** [comment]
@mkarneim It turns out that a lua require does work like a java import this also explains why I couldn't reproduce the suspected bug while debugging:
> [Lua offers a higher-level function to load and run libraries, called require. Roughly, require does the same job as dofile, but with two important differences. First, require searches for the file in a path; second, require controls whether a file has already been run to avoid duplicating the work. Because of these features, require is the preferred function in Lua for loading libraries.](https://www.lua.org/pil/8.1.html)

That means my suggested nil check is completely pointless. I will now rewrite the class files like this:
```lua
require 'net.karneim.luamod.lua.classes.event.PlayerInteractEvent'
class("LeftClickBlockEvent", PlayerInteractEvent)
```
I will still add the code to throw an error when attempting to create a previously registered class:
```lua
assert( _G[name] == nil, "bad argument #%d (a global variable with name '%s' is already defined)", 1, name)
```

**Pull request merged**
